### ISSUE TITLE
Failed to execute 'configureSwapChain' on 'GPUCanvasContext'

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGPU#288]
I tried the RedGPU sample with the latest version of Chrome Canary.
However, every sample gave the same error and the sample could not be displayed.

https://redcamel.github.io/RedGPU/examples/basic/helloWorld/index.html

```javascript
RedGPU.min.mjs:9 
Uncaught (in promise) DOMException: Failed to execute 'configureSwapChain' on 'GPUCanvasContext': rgba8unorm can only support OUTPUT_ATTACHMENT usage
```

**Comment by redcamel** [comment]
@cx20 
修正し始めました。
釘ボンサイ多くの変化があったかですね^^

**Comment by redcamel** [comment]
@cx20 
一度全体的に把握してみるとsetSubDataのほうが多壊れています。
平日に変更点を把握して修正するようにします。

**Comment by redcamel** [comment]
@cx20 
テクスチャビューを作成して管理する部分の変更点があるのは明らかだがもしかしたら助けてくれるほどのポイントはありますか？

現在
1.パーティクルを除く
2.既存のテクスチャキャッシュコメントアウト
での動作は可能になりました。

バッファのsetSubDataはマップされたバッファに移動行けばなることが推測ですが...
もう少し明確なポイントをキャッチ、複数方面にテスト中です。

**Comment by redcamel** [comment]
@cx20 
パーティクルも処理した。
GPUBuffer.setSubData is deprecated。も近いうちに解決そうです。

**Comment by redcamel** [comment]
@cx20 fixed all deprecated API.

**Comment by cx20** [comment]
@redcamel Thanks for fixing. However, I got an error with the [Triangle](https://cx20.github.io/webgpu-test/examples/redgpu/triangle/index.html) sample.

https://cx20.github.io/webgpu-test/examples/redgpu/triangle/index.html

```javascript
BaseMaterial.js:22 
Uncaught (in promise) TypeError: Failed to execute 'createBindGroupLayout' on 'GPUDevice': required member entries is undefined.
    at makeUniformBindLayout (BaseMaterial.js:22)
    at new BaseMaterial (BaseMaterial.js:63)
    at new VertexColorMaterial (index.js:37)
    at RedGPUContext.<anonymous> (index.js:90)
    at RedGPUContext.js:166
```

```javascript
uniformsBindGroupLayoutDescriptor
 {bindings: Array(0)}
  bindings: Array(0)
```

Perhaps the `bindings` needs to be changed to `entries`,.

**Comment by redcamel** [comment]
@cx20 WebGPUのDescriptor仕様が変更されました。
bindings===> entries
二箇所を修正すると、動作します。

before
![image](https://user-images.githubusercontent.com/820587/84150256-9040b000-aa9c-11ea-9d48-55fccc9f1b4d.png)
current
![image](https://user-images.githubusercontent.com/820587/84150229-86b74800-aa9c-11ea-8ab4-1587485d7c78.png)

![image](https://user-images.githubusercontent.com/820587/84150547-f6c5ce00-aa9c-11ea-84eb-38237c9878f0.png)

**Comment by cx20** [comment]
@redcamel  Sorry. It was my mistake. After fixing the sample as you say, it now works with Chrome Canary.
