### ISSUE TITLE
createBufferMapped is deprecated

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGPU#296]
The latest version of Chrome Canary has changed some WebGPU APIs.

PSA for Chromium / Dawn WebGPU API updates 2020-07-28
https://hackmd.io/szV68rOVQ56GYzPJMBko8A

**Comment by redcamel** [comment]
- [ ] setIndexBuffer
 - [ ] GPUVertexStateDescriptor
 - [ ] mappedAtCreation
 - [ ] mapAsync

**Comment by cx20** [comment]
@redcamel Thanks! I have confirmed that it has been resolved as well.
