### ISSUE TITLE
defaultQueue is deprecated 

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGPU#298]
I tried to display the sample below. 
However, it seems that a warning is displayed on the console.
https://redcamel.github.io/RedGPU/examples/basic/helloWorld/index.html

```
The defaultQueue attribute has been deprecated in favor of the queue attribute, and will soon be removed.
```

**Comment by cx20** [comment]
There have been some changes to the WebGPU specification recently, in addition to `defaultQueue`.
I think the following summary of changes will be helpful.
https://hackmd.io/@webgpu/HJdib9rOD

**Comment by cx20** [comment]
I don't think you need help, but I'll link to it for your reference.
https://hackmd.io/@webgpu/BkGB45T8O

**Comment by redcamel** [comment]
@cx20 
RedGPUも最新化を適用するために努力しています。
もう少しお待ちください。^^

**Comment by redcamel** [comment]
@cx20 おかげで急速に修正が行われています。

**Comment by cx20** [comment]
I confirmed that the `RedGPU` samples started working again.
https://redcamel.github.io/RedGPU/examples/basic/helloWorld/index.html
