### ISSUE TITLE
Use the library to convert from GLSL (SPIR-V) to WGSL

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGPU#305]
WebGPU uses WGSL as the standard shader and GLSL (SPIR-V) is no longer supported.

However, the good news. Using a library called `TintWASM`, you can convert from GLSL (SPIR-V) to WGSL with JavaScript.
This library is located in the Babylon.js repository.
https://github.com/BabylonJS/Babylon.js/tree/master/dist/preview%20release/twgsl

The following is reference information. I confirmed on the Babylon.js forum that it's okay to include this library in own project.
https://forum.babylonjs.com/t/can-i-use-the-tintwasm-library-in-the-babylon-js-repository/23673

**Comment by redcamel** [comment]
@cx20 
![image](https://user-images.githubusercontent.com/820587/134889996-0ca6f95f-6e6e-448d-9096-ad8c2c53931b.png)
変換は、うまくいっているが、...
何か浮動小数点演算のwgslに問題があるように見えます。

**Comment by cx20** [comment]
I tried the conversion on the following page. 
https://jsfiddle.net/cx20/vmkaqw2b/

It certainly seems that the accuracy has dropped.
![image](https://user-images.githubusercontent.com/1833979/134909936-37eec736-bbc9-4595-92cb-3fd9ad4229ca.png)

**Comment by redcamel** [comment]
@cx20 
まだ正確なエラーは、よくわかりませんが...
1点以下や....小数点計算の場合....何かエラーがあるようです。
もう少し綿密に調べてみましょう。

**Comment by cx20** [comment]
I have tried the following tools. It seems that the accuracy is reduced by the conversion from `GLSL` to `SPIR-V`.
https://alexaltea.github.io/glslang.js/
![image](https://user-images.githubusercontent.com/1833979/134920797-d1551539-5ffa-4d4d-9980-60d0c9777fcd.png)

**Comment by redcamel** [comment]
@cx20 解決しました。近いうちに更新します。
精密の問題はありますが。安定的に実装されます。

**Comment by redcamel** [comment]
@cx20 The version that works on trial origin has been updated.
https://redcamel.github.io/RedGPU/examples/
